work_dir = './logs/04-13-test-baseline-le-1e-3'
input_resize = (192, 256)
action_map_size = (192, 256)
feature_dim = 576
patch_size = (8, 8)
num_patch_h = 24
num_patch_w = 32
num_patchs = 768
max_length = 18
d_model = 128
d_ff = 128
d_k = 64
d_v = 64
enc_n_layers = 4
dec_n_layers = 4
n_heads = 8
dropout = 0
num_gauss = 5
MDN_hidden_num = 16
postion_method = 'fixed'
device = 'cuda:2'
lr = 0.001
epoch_nums = 100
train_batch_size = 20
val_batch_size = 20
val_step = 5
seed = 1218
weight_decay = 0
lr_scheduler = dict(
    type='MultiStepLR', warmup_epochs=20, milestones=[50, 100], gamma=0.5)
train_gt_nums = 1
reload_path = './model_weights/best_model_and_config/ep85.pth.tar'
sal_gen = True
backbone_grad = False
backbone_lr = 1e-05
eos = False
lambda_1 = 0.3
saliency_attention = True
vgg_fea = False
train_imgs_num = 10000
config = './model_weights/best_model_and_config/config.py'
train = True
inference = True
score = True
options = None
wo_train = True
wo_inference = False
wo_score = True
